spring:
  datasource:
    username: root
    password: 19931125Tu
    url: jdbc:mysql://47.75.90.219:3306/springdb
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /weixin
